services:
  facete-build:
    build: ./facete
    volumes:
      - mvn-cache:/root/.m2
      - app-target:/app/target
    profiles:
      - build

  docker:
    image: docker:dind
    profiles:
      - build
    depends_on:
      facete-build:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - app-target:/app
    # command: ["docker", "load", "-i", "/app/facete-docker-image.tar"]
    command: docker load -i /app/facete-docker-image.tar
  
  facete:
    image: aklakan/facete3-web
    ports:
      - "8088:8080"
    restart: always
    profiles:
      - serve
  
  # jena:
  #   build: ./jena
  #   ports:
  #     - "3030:3030"
  #   volumes:
  #     - mvn-cache:/root/.m2

volumes:
  mvn-cache:
  app-target: